### ISSUE TITLE
How to change text font and font size??

### ISSUE THREAD

**Issue by punitsilversky** [nks5117/KatexUtils#1]
Hi, @nks5117

Thanks for sharing this wonderful library,

I'm here to know about,

Can i change text font, font-size, font-color or any other properties??

Thanks in Advance.

**Comment by nks5117** [comment]
For now, we do not support changing font properties.

However, the KaTeX itself does support some functions related to font styles, such as `\textcolor`, `\bold`, `\large` and `\tiny`. You can use them.

See this document for more information.
https://katex.org/docs/supported.html#style-color-size-and-font

Thanks for the comment.

**Comment by punitsilversky** [comment]
Hi, @nks5117 

Thanks for the response and sharing this useful information, I will try that you suggest

And One more thing that Can i use this library for iOS 12??

Any Suggestions would be great.

Thanks in Advance.

**Comment by nks5117** [comment]
I'm using Combine in this library, which requires iOS 13 or above. So you can not use it for iOS 12 without changing the code. Maybe you can remove the code that is using Combine, and use KVO instead.

[Document for Combine](https://developer.apple.com/documentation/combine)

**Comment by punitsilversky** [comment]
Hi, @nks5117 

Thanks for your quick response and effort, I appreciated that

I will try to update code of combine framework

Thanks!
Punit
