### ISSUE TITLE
KatexUtils(iOS) - Height and Spacing issue in Equations

### ISSUE THREAD

**Issue by mmdHussain** [nks5117/KatexUtils#3]
Having problem in showing the equation in katexview.The top and bottom spacing increase the large equations.

`$$\\displaystyle {1 + \\frac{q^2}{(1-q)}+\\frac{q^6}{(1-q)(1-q^2)}+\\cdots }= \\prod_{j=0}^{\\infty}\\frac{1}{(1-q^{5j+2})(1-q^{5j+3})}, \\quad\\quad \\text{for }\\lvert q\\rvert<1$$`

`"Solve the equation\n$$x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}$$\nAlso. write expression for\n$$\\Re{z} =\\frac{n\\pi \\dfrac{\\theta +\\psi}{2}}{ \\left(\\dfrac{\\theta +\\psi}{2}\\right)^2 + \\left( \\dfrac{1}{2} \\log \\left\\lvert\\dfrac{B}{A}\\right\\rvert\\right)^2}$$"`

The katex code which I'm using as follows
```
    let katexView = KatexView(frame: CGRect(x: 0, y: 0, width: 414, height: 184), latex:  question.latexText, maxSize: nil, options: nil)
                katexView.options = [.displayMode: false, .macros: [#"\RR"#: #"\mathbb{R}"#, #"\f"#: #"#1f(#2)"#]]
                katexView.customCss = ".katex { color: white;font-family: Helvetica Neue;font-size: 20px;text-align: left;display: flex; }"
                
                katexView.$status.sink { [weak self] (status) in
                    
                    guard let _ = self else {
                        return
                    }
                    
                    let height = katexView.intrinsicContentSize.height
                    switch status {
                    case .error(let error):
                        print("\(error.localized())")
                        questions -= 1
                        modifyLibrary.content_questions.append(modifyQuestion)
                        if questions == 0 {
                            fullfilled(modifyLibrary)
                        }
                    case .finished:
                        modifyQuestion.latexHeight = max(height, 50)
                        modifyLibrary.content_questions.append(modifyQuestion)
                        questions -= 1
                        if questions == 0 {
                            fullfilled(modifyLibrary)
                        }
                    default:
                        break
                    }
                }.store(in: &cancellables)
                
```

The height which is returned from katex is 180.The top and bottom spacing is very large.I need to reduce these spacing.

The katexview is in red view and the top and bottom spacing is very large.

![Simulator Screen Shot - iPhone 11 - 2021-08-21 at 17 32 10](https://user-images.githubusercontent.com/17882197/130321156-c23899e3-e0cd-4fab-aae6-4a203c1a286c.png)

```
"Solve the equation\n$$x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}$$\nAlso. write expression for\n$$\\Re{z} =\\frac{n\\pi \\dfrac{\\theta +\\psi}{2}}{ \\left(\\dfrac{\\theta +\\psi}{2}\\right)^2 + \\left( \\dfrac{1}{2} \\log \\left\\lvert\\dfrac{B}{A}\\right\\rvert\\right)^2}$$\n\n$$x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}$$\nAlso. write expression for\n$$\\Re{z} =\\frac{n\\pi \\dfrac{\\theta +\\psi}{2}}{ \\left(\\dfrac{\\theta +\\psi}{2}\\right)^2 + \\left( \\dfrac{1}{2} \\log \\left\\lvert\\dfrac{B}{A}\\right\\rvert\\right)^2}$$\n\n$$x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}$$\nAlso. write expression for\n$$\\Re{z} =\\frac{n\\pi \\dfrac{\\theta +\\psi}{2}}{ \\left(\\dfrac{\\theta +\\psi}{2}\\right)^2 + \\left( \\dfrac{1}{2} \\log \\left\\lvert\\dfrac{B}{A}\\right\\rvert\\right)^2}$$\n\n$$x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}$$\nAlso. write expression for\n$$\\Re{z} =\\frac{n\\pi \\dfrac{\\theta +\\psi}{2}}{ \\left(\\dfrac{\\theta +\\psi}{2}\\right)^2 + \\left( \\dfrac{1}{2} \\log \\left\\lvert\\dfrac{B}{A}\\right\\rvert\\right)^2}$$";
```

![Simulator Screen Shot - iPhone 11 - 2021-08-21 at 18 39 32](https://user-images.githubusercontent.com/17882197/130322853-2ff6958e-cbb1-4bbe-bb4b-8bd07424cacb.png)
![Simulator Screen Shot - iPhone 11 - 2021-08-21 at 18 39 38](https://user-images.githubusercontent.com/17882197/130322854-1a05c0e3-24e8-44ec-ac5d-84ea3a5926d6.png)

**Comment by nks5117** [comment]
Base on the code you provided, I can not reproduce the problem:

![Screen Shot](https://user-images.githubusercontent.com/33224777/131244307-7790b162-1693-44c1-8ae5-615603943e7c.png)

Besides, `KatexView` is only designed for rendering a single math formula. It parses LaTeX text under math mode, which means you need to use `\text{}` function to display a piece of text in your math formula, and you can not use `$` to indicate the range of the formula.

`KatexView` can not handle mixed typesetting of a large amount of text and math formulas, you may need to find other ways to do this.

**Comment by mmdHussain** [comment]
Thanks for reply.
