### ISSUE TITLE
KatexUtils(iOS) - Multiple line breaks are not working

### ISSUE THREAD

**Issue by mmdHussain** [nks5117/KatexUtils#4]
I have equation like these
```
Simplify $$\\frac{x^3-4x^5}{14x+21} \\div \\frac{x^2}{7}$$\n\nsdssdsdsds\n\n\nsdsdsds\n\n\n\n\n\n\n\n\n\n\nSdsdsds
```
In above equation there are multiple line breaks but Katex only break line one time.I'm using these code for line break

```

func latex () -> String {
        var modifyString = self
        if modifyString.first == "$"{
            modifyString.removeFirst()
        }
        
        if modifyString.first == "$"{
            modifyString.removeFirst()
        }
        
        if modifyString.last == "$"{
            modifyString.removeLast()
        }
        
        if modifyString.last == "$"{
            modifyString.removeLast()
        }
        let mString = modifyString.replacingOccurrences(of: "$", with: "")
        
        let lString = mString.replacingOccurrences(of: " ", with: #"\ "#)
        if lString.contains("matrix") {
            let newString = lString.replacingOccurrences(of: "\n", with: #"\\"#)
            return newString
        }
        let newString = lString.replacingOccurrences(of: "\n", with: #"\\"#)
        return newString
    }

```

These equation with multiple line break when put into katex it shows like these

<img width="277" alt="Screenshot 2021-08-21 at 7 14 51 PM" src="https://user-images.githubusercontent.com/17882197/130323724-fafe5f70-ab70-4f16-9a90-32bb8e11c97a.png">

Means katex is not considering vertical empty space with `\\`.It should have vertical space.

If I use below method

```
  let newString = mString.replacingOccurrences(of: "\n", with: #"\\*"#)
```

Then it break line properly but it shows asterisk

<img width="265" alt="Screenshot 2021-08-21 at 7 26 12 PM" src="https://user-images.githubusercontent.com/17882197/130324000-bee4b2bb-d2c6-478b-a96d-04ee0bfd9890.png">

**Comment by nks5117** [comment]
KatexUtils does not use TeX, but KaTeX, which is a JavaScript library for math typesetting. KaTeX is not fully compatible with TeX, it only supports a part of TeX environments and functions. `\\*` is not supported by KaTeX. Check the [document](https://katex.org/docs/supported.html) for details.

And as mentioned in  #[3](https://github.com/nks5117/KatexUtils/issues/3), `KatexView` is only designed for rendering a single math formula, and it does not support mixed typesetting of a large amount of text and math formulas.
